"""The note-store the tools act on. Provided — you do not edit this file."""
from __future__ import annotations

import itertools

_notes: dict[int, dict] = {}
_ids = itertools.count(1)


def reset() -> None:
    global _ids
    _notes.clear()
    _ids = itertools.count(1)


def search_notes(query: str, limit: int = 5) -> str:
    hits = [f"{i}: {n['title']}" for i, n in _notes.items()
            if query.lower() in (n["title"] + " " + n["body"]).lower()]
    return "\n".join(hits[:limit]) or "no matches"


def write_note(title: str, body: str) -> str:
    note_id = next(_ids)
    _notes[note_id] = {"title": title, "body": body}
    return f"created note {note_id}"


def delete_note(note_id: int) -> str:
    if note_id not in _notes:
        raise KeyError(f"no note with id {note_id}")
    del _notes[note_id]
    return f"deleted note {note_id}"
